name: .NET Core Build

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: "0 */2 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
            dotnet-version: 7.0.x

      - name: Run Project
        run: dotnet run --project ./src/DigiKalaDiscounts/DigiKalaDiscounts.csproj -t ${{ secrets.TELEGRAM_ACCESSTOKEN }} -i ${{ secrets.TELEGRAM_CHATID }}

      - name: Verify processed-items folder
        run: |
          if [ -d "./src/DigiKalaDiscounts/processed-items" ]; then
            echo "processed-items folder exists."
          else
            echo "processed-items folder does not exist."
            exit 1
          fi

      - name: List contents of processed-items folder
        run: ls -la ./src/DigiKalaDiscounts/processed-items/

      - name: Push changes to repo          
        run: |      
          git config http.sslVerify false
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git remote add publisher "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"
          git show-ref
          git branch --verbose
          git lfs install
          git checkout main
          git add -A
          git commit -m "Automated publish" || echo "there is nothing to commit, proceed"
          git pull --rebase publisher main
          git push publisher main       

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./src/DigiKalaDiscounts/processed-items/
          cname: api.digikaladiscounts.com
